### ISSUE TITLE
Typos in tests.

### ISSUE THREAD

**Issue by misaz** [laurentiustamate94/iKariera-coding-challenge#1]
I found 2 errors in test clases.

1.) In [CodingChallenges.Tests/TheOutlierIntTest.cs](https://github.com/MicrosoftPrague/iKariera-coding-challenge/blob/master/CodingChallenges.Tests/TheOutlierIntTest.cs) is used class `TheOddInt` instead of `TheOutlierInt`.
2.) In [CodingChallenges.Tests/StopGninnipsMySdrowTest.cs](https://github.com/MicrosoftPrague/iKariera-coding-challenge/blob/master/CodingChallenges.Tests/StopGninnipsMySdrowTest.cs) is `Assert.Equal("This is a tes", actual);` while it would be `Assert.Equal("This is a test", actual);` (missing t in word test)

**Comment by laurentiustamate94** [comment]
thanks for this 🙇
