### ISSUE TITLE
Possible mistake in WeightForWeightTest

### ISSUE THREAD

**Issue by mashabek** [laurentiustamate94/iKariera-coding-challenge#3]
Given an input 
`actual = WeightForWeight.OrderByWeight("2000 10003 1234000 44444444 9999 11 11 22 123");`
Instead of 
`Assert.Equal("11 11 2000 10003 22 123 1234000 44444444 9999", actual);`
should be 
`Assert.Equal("2000 11 11 10003 22 123 1234000 44444444 9999", actual);`

**Comment by vastlik** [comment]
I think it is correct, since they have the same weight, they are compared as strings. See code in python:
```
>>> print("2000" > "11")
True
```
The output is True. Therefore it should be "11 11 2000".

**Comment by laurentiustamate94** [comment]
yes. @vastlik is right. closing this.

thank you for involvement 🙇
